import type { Metadata } from "next";
import Sidebar from "./_components/Sidebar";

import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';

import "./globals.css";
import "normalize.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'g-root g-root_theme_light antialiased'}
      >
        <div className="page">
          <aside>
            <Sidebar />
          </aside>

          <div className="page__content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
